### ISSUE TITLE
Military Calculator doesn't calculate budget

### ISSUE THREAD

**Issue by ModzOnYT** [alexbance/rp-centre#25] opened 2017-06-06 17:59 UTC
Full log of browser console:
https://pastebin.com/raw/Bpkknbg4
Firefox version: 48.0.2
Also tried on Edge/Chrome

**Comment by alexbance** [comment] 2017-06-08 08:55
I'm unable to reproduce this error with my own account, could you provide me with the name of the nation you used?

**Comment by ModzOnYT** [comment] 2017-06-08 13:48
Retinentia is the name of the nation.

**Comment by alexbance** [comment] 2017-06-19 13:48
Looks like we'll need to re-work the formula, to handle negative values.

**Comment by alexbance** [comment] 2017-06-20 16:35
Will be fixed in the next release

**Comment by alexbance** [comment] 2017-07-05 11:01
#43

**Closed** 2017-07-11 10:52 UTC
Labels: bug, pending merge
